"""update company table

Revision ID: 0f05382143ea
Revises: cb787028944f
Create Date: 2019-06-21 19:16:50.296140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f05382143ea'
down_revision = 'cb787028944f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('name', sa.String(length=64), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'name')
    # ### end Alembic commands ###
