"""update field

Revision ID: 40209c99ca27
Revises: 15daee00a9ab
Create Date: 2019-06-28 11:03:53.229413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40209c99ca27'
down_revision = '15daee00a9ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seeker', sa.Column('education', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeker', 'education')
    # ### end Alembic commands ###
