"""add ondelete

Revision ID: 653f82ec9d99
Revises: a48db2de2947
Create Date: 2019-06-22 16:04:05.507790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '653f82ec9d99'
down_revision = 'a48db2de2947'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('company_ibfk_1', 'company', type_='foreignkey')
    op.create_foreign_key(None, 'company', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('job_ibfk_1', 'job', type_='foreignkey')
    op.create_foreign_key(None, 'job', 'company', ['company_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('job_tag_ibfk_1', 'job_tag', type_='foreignkey')
    op.drop_constraint('job_tag_ibfk_2', 'job_tag', type_='foreignkey')
    op.create_foreign_key(None, 'job_tag', 'tag', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'job_tag', 'job', ['job_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('seeker_ibfk_1', 'seeker', type_='foreignkey')
    op.create_foreign_key(None, 'seeker', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seeker', type_='foreignkey')
    op.create_foreign_key('seeker_ibfk_1', 'seeker', 'user', ['user_id'], ['id'])
    op.drop_constraint(None, 'job_tag', type_='foreignkey')
    op.drop_constraint(None, 'job_tag', type_='foreignkey')
    op.create_foreign_key('job_tag_ibfk_2', 'job_tag', 'tag', ['tag_id'], ['id'])
    op.create_foreign_key('job_tag_ibfk_1', 'job_tag', 'job', ['job_id'], ['id'])
    op.drop_constraint(None, 'job', type_='foreignkey')
    op.create_foreign_key('job_ibfk_1', 'job', 'company', ['company_id'], ['id'])
    op.drop_constraint(None, 'company', type_='foreignkey')
    op.create_foreign_key('company_ibfk_1', 'company', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
