"""update education table

Revision ID: 88b7c6534287
Revises: 40209c99ca27
Create Date: 2019-06-28 11:38:15.385950

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '88b7c6534287'
down_revision = '40209c99ca27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education', 'level')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('level', mysql.VARCHAR(length=12), nullable=True))
    # ### end Alembic commands ###
