"""add education table

Revision ID: 938fb3ecfe60
Revises: b7cd12297393
Create Date: 2019-06-28 10:36:09.570407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '938fb3ecfe60'
down_revision = 'b7cd12297393'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('education',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('in_time', sa.DateTime(), nullable=False),
    sa.Column('out_time', sa.DateTime(), nullable=False),
    sa.Column('level', sa.String(length=12), nullable=True),
    sa.Column('pro', sa.String(length=32), nullable=False),
    sa.Column('seeker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seeker_id'], ['seeker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('seeker', sa.Column('age', sa.SmallInteger(), nullable=True))
    op.add_column('seeker', sa.Column('education', sa.String(length=12), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('seeker', 'education')
    op.drop_column('seeker', 'age')
    op.drop_table('education')
    # ### end Alembic commands ###
