"""add experience table

Revision ID: b7cd12297393
Revises: 2ee884f7cc28
Create Date: 2019-06-28 08:55:27.720717

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7cd12297393'
down_revision = '2ee884f7cc28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('experiences',
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('department', sa.String(length=32), nullable=True),
    sa.Column('job_name', sa.String(length=32), nullable=False),
    sa.Column('in_time', sa.DateTime(), nullable=False),
    sa.Column('out_time', sa.DateTime(), nullable=False),
    sa.Column('work_content', sa.TEXT(), nullable=True),
    sa.Column('seeker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['seeker_id'], ['seeker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('experiences')
    # ### end Alembic commands ###
