"""add resume table

Revision ID: b8bea70fe878
Revises: 3867a39b4bef
Create Date: 2019-06-27 19:24:30.819188

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b8bea70fe878'
down_revision = '3867a39b4bef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeker_job')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeker_job',
    sa.Column('seeker_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('job_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('freed_back', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], name='seeker_job_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['seeker.id'], name='seeker_job_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seeker_id', 'job_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
