"""update education table

Revision ID: b9c0bb591693
Revises: 88b7c6534287
Create Date: 2019-06-28 11:38:56.941321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b9c0bb591693'
down_revision = '88b7c6534287'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('education', sa.Column('level', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('education', 'level')
    # ### end Alembic commands ###
