"""update 

Revision ID: c2896b4e99b3
Revises: 0f05382143ea
Create Date: 2019-06-21 19:50:45.590089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2896b4e99b3'
down_revision = '0f05382143ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tag_name', table_name='tag')
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.create_index('ix_tag_name', 'tag', ['name'], unique=False)
    # ### end Alembic commands ###
