"""update company table

Revision ID: cb787028944f
Revises: f8b12c9b32fd
Create Date: 2019-06-21 18:52:31.161077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb787028944f'
down_revision = 'f8b12c9b32fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('addr', sa.String(length=128), nullable=True))
    op.add_column('company', sa.Column('logo', sa.String(length=256), nullable=True))
    op.add_column('company', sa.Column('slogan', sa.String(length=64), nullable=True))
    op.add_column('company', sa.Column('website', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company', 'website')
    op.drop_column('company', 'slogan')
    op.drop_column('company', 'logo')
    op.drop_column('company', 'addr')
    # ### end Alembic commands ###
