"""seeker job many to many

Revision ID: eb3881665de3
Revises: 653f82ec9d99
Create Date: 2019-06-24 13:24:46.672640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb3881665de3'
down_revision = '653f82ec9d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seeker_job',
    sa.Column('seeker_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seeker_id'], ['seeker.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('seeker_id', 'job_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('seeker_job')
    # ### end Alembic commands ###
